apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  namespace: laravel
spec:
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel
        ports:
        - containerPort: 8000
        image: bitnami/laravel:11.0.8
        env:
        - name: LARAVEL_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: laravel-configmap
              key: host

        - name: LARAVEL_DATABASE_PORT_NUMBER
          valueFrom:
            configMapKeyRef:
              name: laravel-configmap
              key: port

        - name: LARAVEL_DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: laravel-configmap
              key: user

        - name: LARAVEL_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: laravel-configmap
              key: name

        - name: LARAVEL_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: database_password