apiVersion: v1
kind: LimitRange
metadata:
  name: limit-laravel
  namespace: laravel
spec:
  limits:
    - default:
        cpu: "800m"
        memory: "512Mi"
      max:
        cpu: "1"
        memory: "700Mi"
      min:
        cpu: "800m"
        memory: "512Mi"
      type: Container