apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deploy
  namespace: laravel
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.3
        env:
        - name: MARIADB_USER
          valueFrom:
            configMapKeyRef:
              name: mariadb-configmap
              key: database_user

        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: database_password

        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: database_root_password
              
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mariadb-configmap
              key: database_name