apiVersion: v1
kind: Service
metadata:
  name: laravel-svc-2
  labels:
    app: laravel
spec:
  type: NodePort
  selector:
    app: laravel
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
